<a href="https://colab.research.google.com/github/Amrutasutrave/colab_files/blob/main/cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv("/content/cars (1).csv")
df.head()

'''
1.read data----basic anaysis
2.Missing values and encoding
3.Build a baseline model-'''
#step 1 replace '?' with NAN
df['normalized-losses'].replace('?',np.nan,inplace=True)
df['horsepower'].replace('?',np.nan,inplace=True)
#step 2--changing the data type  cat colum into float
df['normalized-losses']=df['normalized-losses'].astype('float64')
df['horsepower']=df['normalized-losses'].astype('float64')
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan,strategy='mean')
#separate feature and target
X=df.iloc[:,:-1]  #all column except last
Y=df.iloc[:,-1] #only last col
#fit nan with mean
X[['normalized-losses','horsepower']]=si.fit_transform(X[['normalized-losses','horsepower']])
X.head()
#separating cat columns
cat_col=X.select_dtypes(object).columns
cat_col
#splitting training and test data
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.3,random_state=1)
#Encoding
for col in cat_col:
    le=LabelEncoder() #le is an object of label encoder
    xtrain[col]=le.fit_transform(xtrain[col])
    xtest[col]=le.transform(xtest[col])
xtest

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
78           2              161.0    11          1           2             1   
97           1              103.0    12          1           4             1   
151          1               87.0    19          1           2             1   
44           1              122.0     6          1           3             1   
40           0               85.0     5          1           3             1   
..         ...                ...   ...        ...         ...           ...   
39           0               85.0     5          1           3             1   
110          0              122.0    13          0           4             2   
164          1              168.0    19          1           2             2   
56           3              150.0     8          1           2             2   
176         -1               65.0    19          1           3             1   

     engine-location  width  height  engine-type  engine-size  horsepower  \
78                 0   64.4    50.8            3           92       161.0   
97                 0   63.8    53.5            3           97       103.0   
151                0   63.6    54.5            3           92        87.0   
44                 0   63.6    52.0            3           90       122.0   
40                 0   62.5    54.1            3          110        85.0   
..               ...    ...     ...          ...          ...         ...   
39                 0   65.2    54.1            3          110        85.0   
110                0   68.4    58.7            2          152       122.0   
164                0   64.0    52.6            3           98       168.0   
56                 0   65.7    49.6            6           70       150.0   
176                0   66.5    54.9            3          122        65.0   

     city-mpg  highway-mpg  
78         31           38  
97         31           37  
151        31           38  
44         38           43  
40         27           33  
..        ...          ...  
39         27           33  
110        25           25  
164        29           34  
56         17           23  
176        27           32  

[62 rows x 14 columns]

In [ ]:
#Linear Regression model
lr=LinearRegression()
lr.fit(xtrain,ytrain)
#testing model on training data
from sklearn.metrics import r2_score
y_pred=lr.predict(xtrain)
r2_score(ytrain,y_pred)
#testing model on testing data
from sklearn.metrics import r2_score
y_pred=lr.predict(xtest)
r2_score(ytest,y_pred)
lr.score(xtrain,ytrain)
lr.score(xtest,ytest)

0.800307244170246

as r2 fot train  data>2 score test data,this is an overmodel

In [ ]:
#regularization-----used to minimize data---ridge&lasso
from sklearn.linear_model import Lasso,Ridge


In [ ]:
#ridge regularization
l2=Ridge(0.01)
l2.fit(xtrain,ytrain)

Ridge(alpha=0.01)

In [ ]:
l2.score(xtest,ytest)

0.8004214219582045

In [ ]:
l2.coef_

array([ 4.47389123e+01,  1.12684988e+00, -2.04285856e+02, -7.74749633e+02,
       -2.02976661e+02,  1.82938204e+03,  1.57903650e+04,  7.50791247e+02,
        4.00806219e+02,  3.23889520e+02,  9.37217987e+01,  1.12684992e+00,
        3.49219298e+02, -4.33560168e+02])

In [ ]:
#taking diff values of erro to l2 model
for alpha in range(1,10):
  l2=Ridge(alpha)
  l2.fit(xtrain,ytrain)
  test_score=l2.score(xtest,ytest)
  print('Alpha',alpha)
  print('Test score',test_score)
  print('------------------------------------')

Alpha 1
Test score 0.8063784661718955
------------------------------------
Alpha 2
Test score 0.8082482284216761
------------------------------------
Alpha 3
Test score 0.8090039293521639
------------------------------------
Alpha 4
Test score 0.8093440160202401
------------------------------------
Alpha 5
Test score 0.8094919679995507
------------------------------------
Alpha 6
Test score 0.8095367651885574
------------------------------------
Alpha 7
Test score 0.8095198513904858
------------------------------------
Alpha 8
Test score 0.8094630080973961
------------------------------------
Alpha 9
Test score 0.8093788406290283
------------------------------------


In [ ]:
'''after an alpha val 2, we can observe that small change in r2 score therefore the ridge
 with alpha =2 is a '''

'after an alpha val 2, we can observe that small change in r2 score therefore the ridge\n with alpha =2 is a '

In [ ]:
#lasso
for alpha in range(100,151,10):
  l2=Lasso(alpha)
  l2.fit(xtrain,ytrain)
  test_score=l2.score(xtest,ytest)
  print('Alpha',alpha)
  print('Test score',test_score)
  print('------------------------------------')

Alpha 100
Test score 0.8087089626767562
------------------------------------
Alpha 110
Test score 0.8091467065043798
------------------------------------
Alpha 120
Test score 0.8095091370649387
------------------------------------
Alpha 130
Test score 0.8097965219954009
------------------------------------
Alpha 140
Test score 0.8100083403020953
------------------------------------
Alpha 150
Test score 0.8101445721384172
------------------------------------


In [ ]:
l2=Ridge(50)
l2.fit(xtest,ytest)
l2.coef_

array([  28.29697442,    0.71540709, -180.24787137, -138.60360037,
       -120.59204121,  550.2422454 ,    0.        ,  507.20246776,
         85.82763834,  -42.24480375,  115.63254527,    0.71540709,
       -242.31529729,   64.91042102])

In [ ]:
l2=Ridge(2)
l2.fit(xtest,ytest)
l2.coef_

array([ 141.0635808 ,   -4.00498133, -224.35750857, -643.83110812,
       -139.34657588, 2434.11819361,    0.        ,  614.47305746,
         59.36573512, -151.19411892,  106.43363293,   -4.00498133,
       -485.74547075,  320.04845566])

In [ ]:
l2=Ridge(130)
l2.fit(xtest,ytest)
l2.coef_

array([   3.38970957,    1.41174894, -158.77382225,  -72.7903293 ,
        -57.55766646,  249.84604132,    0.        ,  314.62298694,
         82.00865491,  -22.85169408,  122.1263665 ,    1.41174894,
       -170.20372953,  -22.15351576])

In [ ]:
#cross validation-------------useful for if we have small dataset
from sklearn.model_selection import cross_val_score

In [ ]:
catcol=X.select_dtypes(object).columns

In [ ]:
for col in catcol:
  le=LabelEncoder()
  X[col]=le.fit_transform(X[col])
  X.head()

In [ ]:
cross_val_score(l2,X,Y,cv=4)  #returns r2 score for all 4 parts of data


array([0.76627337, 0.846364  , 0.48046812, 0.42693307])

In [ ]:
cross_val_score(l1,X,Y,cv=4)  #returns r2 score for all 4 parts of data

NameError: name 'l1' is not defined

In [ ]:
#simple linear regression dataset study